name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenchement du workflow lorsqu'il y a un push sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation de l'environnement Ubuntu pour exécuter le job

    steps:
      # Étape 1: Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2  # Cloner ton dépôt sur l'environnement d'exécution

      # Étape 2: Se connecter à Docker Hub en utilisant les secrets GitHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Action pour se connecter à Docker Hub
        with:
          username: ${{ secrets.nsengimana47 }}  # Récupère ton nom d'utilisateur Docker Hub depuis les secrets
          password: ${{ secrets.AbbeillenoirK022# }}  # Récupère ton mot de passe Docker Hub depuis les secrets

      # Étape 3: Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t nsengimana47/flowatch:latest .  # Remplace par ton nom d'utilisateur et le nom de ton image

      # Étape 4: Pousser l'image Docker vers Docker Hub
      - name: Push Docker image
        run: |
          docker push nsengimana47/flowatch:latest  # Remplace par ton nom d'utilisateur et le nom de ton image
